got it all going with tls_mode=none
changes:

- turn off tls by default... for now
- got slave servers running
- fixed port tunnelling for vault ui and nomad ui, was using 127.0.0.1 always instead of the bound addresses
- keyrings don't exist on slaves, so don't do anything with them

todo:

- for slaves, don't show consul ui and nomad ui strings on local_end as they probably don't exist
- demote bootstrap consul server to agent after successful deployment of masters (or cluster)
- experiment with using nomad jobs for local TLS cert renewals and issue
- remove keyring code, seems to all be working correctly now via the config param

diff --git a/helpers/scripts/service_configure b/helpers/scripts/service_configure
--- a/helpers/scripts/service_configure
+++ b/helpers/scripts/service_configure
@@ -7,19 +7,6 @@ echo "<service_configure $1>"
 # Arguments
 service="$1"
 
-# Clean
-function finish {
-	if sudo systemctl is-enabled "$service"; then
-		sudo systemctl status "$service" -l
-		# determine executable
-		# service_exec="$(grep ExecStart < "/etc/systemd/system/$service.service" | sed 's/ExecStart=//')"
-		# $service_exec
-		# sudo journalctl -u "$service"
-		# sudo journalctl -f -u "$service"
-	fi
-}
-trap finish EXIT
-
 # Variables
 user="$(cat "../data/input/${service}_user")"
 group="$(cat "../data/input/${service}_group")"
@@ -49,7 +36,16 @@ echo "Enabling service for $service..."
 sudo systemctl enable "$service.service"
 
 echo "Starting service for $service..."
-sudo systemctl restart "$service"
+if ! sudo systemctl restart "$service"; then
+	echo 'failed to start...'
+	echo 'here is the service status:'
+	sudo systemctl status "$service" -l
+	echo 'here are the process logs:'
+	sudo journalctl -u "$service"
+	echo 'and here is the manual execution:'
+	service_exec="$(grep ExecStart < "/etc/systemd/system/$service.service" | sed 's/ExecStart=//')"
+	$service_exec
+fi
 sleep 2
 
 echo '</service_configure>'
